name: Issue Logger
on:
   issues:
        types:
            - opened
            - closed
            - reopened
jobs:
    Print-Details:
        runs-on: ubuntu-latest
        steps:
            - name: Print gh object
              run: echo "${{toJSON(github.event)}}"