name: Unit Tests
on: 
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/workflows/*'  # will execute workflow only if files outside of workflow path are changed
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install Dependencies
              run: |
                    npm ci
                    cd client
                    npm ci
            - name: Run Tests - backend
              run: npm run test-backend
            - name: Run Tests - frontend
              run: npm run test-frontend
    build-and-deploy:
        needs: unit-tests  # should run only after unit-test job succeeds
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install Dependencies
              run: |
                    cd client
                    npm ci
            - name: Build
              run: |
                    cd client
                    npm run build
            - name: Deploy
              run: echo "Dummy deployment"
            


